[package]
name = "table_macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.104", features = ["full", "parsing"] }
quote = "1.0.40"
proc-macro2 = "1.0.95"
darling = "0.21.0"
serde_json = "1.0.142"