[package]
name = "aerielle"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.11.1"
minijinja = { version = "2.11.0", features = ["loader"] }
futures = "0.3.31"
sqlx = { version = "0.8.6", features = ["sqlite", "mysql", "postgres"] }